<?php
defined('MYAAC') or die('Direct access not allowed!');

return [
    'general_rules' => [
        'Use o Boss Finder no templo para escolher o boss e ser teleportado ao waypoint da alavanca.',
        'O cooldown começa ao puxar a alavanca (não ao matar o boss).',
        'Cooldown padrão: aproximadamente 20 horas (Bosstiary).',
        'Com cooldown ativo: o jogador não teleporta pelo Finder; não consegue reentrar na sala; não passa pelo corredor do boss.',
        'Cada boss utiliza o nome REAL da criatura para registrar cooldown.',
        'O nome exibido no Boss Finder pode ser apenas visual.',
    ],
    'rule_icons' => [
        ['symbol' => '⏳', 'label' => 'Cooldown'],
        ['symbol' => '✦', 'label' => 'Teleporte'],
        ['symbol' => '⚔', 'label' => 'Boss'],
        ['symbol' => '◆', 'label' => 'Requisitos'],
        ['symbol' => '▲', 'label' => 'Progressão'],
    ],
    'solo_bosses' => [
        ['visual' => 'Arbaziloth', 'real' => 'Arbaziloth', 'slug' => 'arbaziloth', 'cooldown' => 'Individual, ~20h ao puxar a alavanca', 'mechanic' => 'Corredor + alavanca', 'flow' => 'Finder → corredor/alavanca → puxar → teleporte para arena.', 'notes' => 'Bloqueio completo enquanto estiver em cooldown.'],
        ['visual' => 'Brainstealer', 'real' => 'The Brainstealer', 'slug' => 'brainstealer', 'cooldown' => '~20h', 'mechanic' => 'Spawn direto', 'flow' => 'Mecânica simplificada: spawn direto do boss.', 'notes' => ''],
        ['visual' => 'Dread Maiden', 'real' => 'The Dread Maiden', 'slug' => 'dreadmaiden', 'cooldown' => '~20h', 'mechanic' => 'Spawn direto', 'flow' => 'Mesmo sistema do Brainstealer.', 'notes' => ''],
        ['visual' => 'Drume', 'real' => 'Drume', 'slug' => 'drume', 'cooldown' => 'Individual, ~20h', 'mechanic' => 'Tile de entrada', 'flow' => 'Finder → tile de entrada.', 'notes' => 'Com cooldown: bloqueia movimento e informa tempo restante.'],
        ['visual' => 'Faceless', 'real' => 'Faceless Bane', 'slug' => 'facelessbane', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão Boss Lever.', 'notes' => ''],
        ['visual' => 'Leiden', 'real' => 'Ravenous Hunger', 'slug' => 'leiden', 'cooldown' => 'Registrado em Ravenous Hunger', 'mechanic' => 'Cults of Tibia', 'flow' => 'Boss final da luta; mantém mecânica Cults of Tibia.', 'notes' => ''],
        ['visual' => 'Lulu', 'real' => 'Urmahlullu the Immaculate', 'slug' => 'lulu', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão.', 'notes' => ''],
        ['visual' => 'Magma Bubble', 'real' => 'Magma Bubble', 'slug' => 'magmabubble', 'cooldown' => '~20h', 'mechanic' => 'Simplificada', 'flow' => 'Sem ondas End of Days; sem cristais; boss nasce direto.', 'notes' => ''],
        ['visual' => 'Megasylvan Yselda', 'real' => 'Megasylvan Yselda', 'slug' => 'megasylvanyselda', 'cooldown' => '~20h', 'mechanic' => 'Boss Lever', 'flow' => 'Sistema padrão Boss Lever.', 'notes' => ''],
        ['visual' => 'Mitmah', 'real' => 'Mitmah Vanguard', 'slug' => 'mitmah', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão.', 'notes' => ''],
        ['visual' => 'Oberon', 'real' => 'Grand Master Oberon', 'slug' => 'oberon', 'cooldown' => '~20h', 'mechanic' => 'Simplificada', 'flow' => 'Sem frases/imunidade; dano liberado desde o início.', 'notes' => ''],
        ['visual' => 'Pale Worm', 'real' => 'The Pale Worm', 'slug' => 'paleworm', 'cooldown' => '~20h', 'mechanic' => 'Quest final', 'flow' => 'Boss final da quest.', 'notes' => ''],
        ['visual' => 'Primal', 'real' => 'The Primal Menace', 'slug' => 'primal', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão.', 'notes' => ''],
        ['visual' => 'Ratmiral', 'real' => 'Ratmiral Blackwhiskers', 'slug' => 'ratmiral', 'cooldown' => '~20h', 'mechanic' => 'Entrada + alavanca', 'flow' => 'Finder leva próximo da entrada; alavanca teleporta direto para arena.', 'notes' => ''],
        ['visual' => 'Scarlet', 'real' => 'Scarlett Etzel', 'slug' => 'scarlet', 'cooldown' => '~20h', 'mechanic' => 'Simplificada', 'flow' => 'Espelho desativado; armadura removida.', 'notes' => ''],
        ['visual' => 'Soulwar', 'real' => "Goshnar's Malice, Megalomania, Hatred, Spite", 'slug' => 'goshnarmalice', 'cooldown' => 'Individual por boss', 'mechanic' => '4 bosses independentes', 'flow' => 'Todos independentes; sem progressão compartilhada.', 'notes' => 'Escolha cada Goshnar separadamente no Finder.'],
        ['visual' => 'The Fear Feaster', 'real' => 'The Fear Feaster', 'slug' => 'thefearfeaster', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão.', 'notes' => ''],
        ['visual' => 'The Monster', 'real' => 'The Monster', 'slug' => 'themonster', 'cooldown' => '~20h', 'mechanic' => 'Padrão', 'flow' => 'Sistema padrão.', 'notes' => ''],
        ['visual' => 'The Unwelcome', 'real' => 'The Unwelcome', 'slug' => 'theunwelcome', 'cooldown' => '~20h', 'mechanic' => 'Feaster of Souls', 'flow' => 'Sistema padrão Feaster of Souls.', 'notes' => ''],
        ['visual' => 'Timira', 'real' => 'Timira the Many-Headed', 'slug' => 'timira', 'cooldown' => '~20h', 'mechanic' => 'Entrada próxima', 'flow' => 'Finder leva próximo da arena; menos correria até o boss.', 'notes' => ''],
    ],
    'progression_systems' => [
        [
            'id' => 'dream-courts',
            'name' => 'Dream Courts',
            'minis' => ['Plagueroot', 'Malofur Mangrinder', 'Maxxenius', 'Alptramun', 'Izcandar The Banished'],
            'final' => 'The Nightmare Beast',
            'mini_count' => 5,
            'rules' => [
                'Cada mini possui cooldown individual.',
                'Todos utilizam a mesma arena.',
                'O time inteiro precisa selecionar o mesmo mini.',
                'Se a sala estiver ocupada: mostrar aviso para aguardar.',
                'Não existe rotação diária.',
                'O boss enfrentado é o escolhido no Finder.',
                'Ao completar os 5 minis: libera The Nightmare Beast.',
                'Após usar a alavanca do Nightmare Beast: zera o progresso.',
            ],
        ],
        [
            'id' => 'grave-danger',
            'name' => 'Grave Danger / GT',
            'minis' => ['Count Vlarkorth', 'Duke Krule', 'Earl Osam', 'Lord Azaram', 'Sir Nictros'],
            'final' => 'King Zelos',
            'mini_count' => 5,
            'rules' => [
                'Cooldown individual por mini.',
                'Precisa completar os 5 minis.',
                'Ao fazer Zelos: zera progresso.',
            ],
        ],
        [
            'id' => 'ferumbras',
            'name' => 'Ferumbras Ascendant',
            'minis' => ['Plagirath', 'Ragiaz', 'Razzagorn', 'Tarbaz', 'Zamulosh', 'Shulgrax', 'Mazoran', 'The Lord of the Lice'],
            'final' => 'Ascending Ferumbras',
            'mini_count' => 8,
            'rules' => [
                'Progresso salvo por mini.',
                'Precisa completar os 8.',
                'Após fazer Ferumbras: zera tudo.',
            ],
        ],
        [
            'id' => 'sanguine',
            'name' => 'Sanguine / Rotten Blood',
            'minis' => ['Vermiath', 'Murcion', 'Chagorz', 'Ichgahal'],
            'final' => 'Bakragore',
            'mini_count' => 4,
            'rules' => [
                'Cooldown individual.',
                'Precisa completar os 4 minis.',
                'Final reseta progresso.',
            ],
        ],
    ],
    'summary_table' => [
        ['system' => 'Dream Courts', 'minis' => 5, 'final' => 'The Nightmare Beast', 'reset' => 'Sim'],
        ['system' => 'Grave Danger', 'minis' => 5, 'final' => 'King Zelos', 'reset' => 'Sim'],
        ['system' => 'Ferumbras Ascendant', 'minis' => 8, 'final' => 'Ascending Ferumbras', 'reset' => 'Sim'],
        ['system' => 'Sanguine', 'minis' => 4, 'final' => 'Bakragore', 'reset' => 'Sim'],
    ],
];
