<?php
defined('MYAAC') or die('Direct access not allowed!');

return [
    'tokenId' => 64087,
    'tokenName' => 'Roulette Token',
    'spinOptions' => [1, 5, 10, 25, 50, 100],
    'spinningBonus' => [
        ['spins' => 25, 'reward' => '2x Roulette Tokens', 'itemId' => 64087, 'count' => 2],
        ['spins' => 50, 'reward' => '1x Addon Casket', 'itemId' => 64040, 'count' => 1],
        ['spins' => 75, 'reward' => '1x Mount Casket', 'itemId' => 64085, 'count' => 1],
        ['spins' => 100, 'reward' => '1x Surprise Casket', 'itemId' => 64101, 'count' => 1],
    ],
    'roulettes' => [
        ['id' => 'norte', 'name' => 'Roleta do Norte'],
        ['id' => 'esquerda', 'name' => 'Roleta da Esquerda'],
        ['id' => 'sul', 'name' => 'Roleta do Sul'],
    ],
    'commons' => [
    ['id' => 61621, 'name' => 'purified genesis longbow', 'tier' => 'common'],
    ['id' => 61622, 'name' => 'purified genesis crossbow', 'tier' => 'common'],
    ['id' => 64086, 'name' => 'RavynCore coins', 'tier' => 'common'],
    ['id' => 61869, 'name' => 'RavynCore Token', 'tier' => 'common'],
    ['id' => 37110, 'name' => 'exalted core', 'tier' => 'common'],
    ['id' => 61862, 'name' => 'magic spark', 'tier' => 'common'],
    ['id' => 60581, 'name' => 'stone dust', 'tier' => 'common'],
    ['id' => 16129, 'name' => 'major crystalline token', 'tier' => 'common'],
    ['id' => 35563, 'name' => 'magic shield potion', 'tier' => 'common'],
    ['id' => 61865, 'name' => 'green spark', 'tier' => 'common'],
    ['id' => 61866, 'name' => 'yellow spark', 'tier' => 'common'],
    ['id' => 61867, 'name' => 'red spark', 'tier' => 'common'],
    ['id' => 36723, 'name' => 'kooldown-aid', 'tier' => 'common'],
    ['id' => 36724, 'name' => 'strike enhancement', 'tier' => 'common'],
    ['id' => 36725, 'name' => 'stamina extension', 'tier' => 'common'],
    ['id' => 36726, 'name' => 'charm upgrade', 'tier' => 'common'],
    ['id' => 36727, 'name' => 'wealth duplex', 'tier' => 'common'],
    ['id' => 36728, 'name' => 'bestiary betterment', 'tier' => 'common'],
    ['id' => 36729, 'name' => 'fire resilience', 'tier' => 'common'],
    ['id' => 36730, 'name' => 'ice resilience', 'tier' => 'common'],
    ['id' => 36731, 'name' => 'earth resilience', 'tier' => 'common'],
    ['id' => 36732, 'name' => 'energy resilience', 'tier' => 'common'],
    ['id' => 36733, 'name' => 'holy resilience', 'tier' => 'common'],
    ['id' => 36734, 'name' => 'death resilience', 'tier' => 'common'],
    ['id' => 36735, 'name' => 'physical resilience', 'tier' => 'common'],
    ['id' => 36736, 'name' => 'fire amplification', 'tier' => 'common'],
    ['id' => 36737, 'name' => 'ice amplification', 'tier' => 'common'],
    ['id' => 36738, 'name' => 'earth amplification', 'tier' => 'common'],
    ['id' => 36739, 'name' => 'energy amplification', 'tier' => 'common'],
    ['id' => 36740, 'name' => 'holy amplification', 'tier' => 'common'],
    ['id' => 36741, 'name' => 'death amplification', 'tier' => 'common'],
    ['id' => 36742, 'name' => 'physical amplification', 'tier' => 'common'],
    ['id' => 28485, 'name' => 'strawberry cupcake', 'tier' => 'common'],
    ['id' => 28484, 'name' => 'blueberry cupcake', 'tier' => 'common'],
    ['id' => 61560, 'name' => 'item 61560', 'tier' => 'common'],
    ['id' => 61556, 'name' => 'item 61556', 'tier' => 'common'],
    ['id' => 61558, 'name' => 'item 61558', 'tier' => 'common'],
    ['id' => 61554, 'name' => 'item 61554', 'tier' => 'common'],
    ['id' => 61559, 'name' => 'item 61559', 'tier' => 'common'],
    ['id' => 61555, 'name' => 'item 61555', 'tier' => 'common'],
    ['id' => 61561, 'name' => 'item 61561', 'tier' => 'common'],
    ['id' => 61557, 'name' => 'item 61557', 'tier' => 'common'],
    ],
    'rares' => [
    ['id' => 64040, 'name' => 'addon casket outfit 1', 'tier' => 'rare'],
    ['id' => 64041, 'name' => 'addon casket outfit 2', 'tier' => 'rare'],
    ['id' => 64042, 'name' => 'addon casket outfit 3', 'tier' => 'rare'],
    ['id' => 64043, 'name' => 'addon casket outfit 4', 'tier' => 'rare'],
    ['id' => 64101, 'name' => 'surprise casket', 'tier' => 'rare'],
    ['id' => 64087, 'name' => 'Roulette Token', 'tier' => 'rare'],
    ['id' => 64085, 'name' => 'mount casket', 'tier' => 'rare'],
    ['id' => 43946, 'name' => 'item 43946', 'tier' => 'rare'],
    ['id' => 43947, 'name' => 'item 43947', 'tier' => 'rare'],
    ['id' => 43948, 'name' => 'item 43948', 'tier' => 'rare'],
    ['id' => 43949, 'name' => 'item 43949', 'tier' => 'rare'],
    ['id' => 63100, 'name' => 'item 63100', 'tier' => 'rare'],
    ['id' => 63101, 'name' => 'item 63101', 'tier' => 'rare'],
    ['id' => 63099, 'name' => 'item 63099', 'tier' => 'rare'],
    ['id' => 39546, 'name' => 'primal bag', 'tier' => 'rare'],
    ['id' => 43898, 'name' => 'bag you covet', 'tier' => 'rare'],
    ['id' => 34109, 'name' => 'bag you desire', 'tier' => 'rare'],
    ['id' => 63787, 'name' => 'boss points', 'tier' => 'rare'],
    ['id' => 63743, 'name' => 'ratmiral box', 'tier' => 'rare'],
    ['id' => 63744, 'name' => 'brainstealer box', 'tier' => 'rare'],
    ['id' => 63745, 'name' => 'timira box', 'tier' => 'rare'],
    ['id' => 63748, 'name' => 'oberon box', 'tier' => 'rare'],
    ['id' => 63746, 'name' => 'drume box', 'tier' => 'rare'],
    ['id' => 63747, 'name' => 'scarlett box', 'tier' => 'rare'],
    ['id' => 63749, 'name' => 'plunder patriarch box', 'tier' => 'rare'],
    ['id' => 63750, 'name' => 'nightmare beast box', 'tier' => 'rare'],
    ['id' => 63751, 'name' => 'arbaziloth box', 'tier' => 'rare'],
    ['id' => 63752, 'name' => 'soulwar box', 'tier' => 'rare'],
    ['id' => 63753, 'name' => 'sanguine box', 'tier' => 'rare'],
    ['id' => 63754, 'name' => "gaz'haragoth box", 'tier' => 'rare'],
    ['id' => 63755, 'name' => 'zelos box', 'tier' => 'rare'],
    ['id' => 63756, 'name' => 'mitmah box', 'tier' => 'rare'],
    ['id' => 63757, 'name' => 'amber box', 'tier' => 'rare'],
    ['id' => 63758, 'name' => 'sugar box', 'tier' => 'rare'],
    ['id' => 63759, 'name' => 'monster box', 'tier' => 'rare'],
    ['id' => 63193, 'name' => 'warzone box', 'tier' => 'rare'],
    ['id' => 61713, 'name' => 'destruction box', 'tier' => 'rare'],
    ['id' => 61703, 'name' => 'pale box', 'tier' => 'rare'],
    ],
    'ultraRares' => [
    ['id' => 64114, 'name' => 'ultra rare scroll', 'tier' => 'ultra'],
    ],
];
