<?php
defined('MYAAC') or die('Direct access not allowed!');

return [
    63743 => [
        'name' => 'Ratmiral Box',
        'loot' => [
            ['id' => 35523, 'name' => 'exotic amulet'],
            ['id' => 35517, 'name' => 'bast legs'],
            ['id' => 50270, 'name' => 'bambus jo'],
            ['id' => 35516, 'name' => 'exotic legs'],
            ['id' => 35518, 'name' => 'jungle bow'],
            ['id' => 35514, 'name' => 'jungle flail'],
            ['id' => 35524, 'name' => 'jungle quiver'],
            ['id' => 35521, 'name' => 'jungle rod'],
            ['id' => 50186, 'name' => 'jungle survivor legs'],
            ['id' => 35522, 'name' => 'jungle wand'],
            ['id' => 35520, 'name' => 'make-do boots'],
            ['id' => 35519, 'name' => 'makeshift boots'],
        ],
    ],
    63744 => [
        'name' => 'Brainstealer Box',
        'loot' => [
            ['id' => 36664, 'name' => 'eldritch bow'],
            ['id' => 36667, 'name' => 'eldritch breeches'],
            ['id' => 36657, 'name' => 'eldritch claymore'],
            ['id' => 36670, 'name' => 'eldritch cowl'],
            ['id' => 36835, 'name' => 'eldritch crystal'],
            ['id' => 36663, 'name' => 'eldritch cuirass'],
            ['id' => 36672, 'name' => 'eldritch folio'],
            ['id' => 36661, 'name' => 'eldritch greataxe'],
            ['id' => 36671, 'name' => 'eldritch hood'],
            ['id' => 36666, 'name' => 'eldritch quiver'],
            ['id' => 36674, 'name' => 'eldritch rod'],
            ['id' => 36656, 'name' => 'eldritch shield'],
            ['id' => 36673, 'name' => 'eldritch tome'],
            ['id' => 36668, 'name' => 'eldritch wand'],
            ['id' => 36659, 'name' => 'eldritch warmace'],
            ['id' => 50169, 'name' => 'eldritch crescent moon spade'],
            ['id' => 36665, 'name' => 'gilded eldritch bow'],
            ['id' => 36658, 'name' => 'gilded eldritch claymore'],
            ['id' => 36662, 'name' => 'gilded eldritch greataxe'],
            ['id' => 36675, 'name' => 'gilded eldritch rod'],
            ['id' => 36669, 'name' => 'gilded eldritch wand'],
            ['id' => 36660, 'name' => 'gilded eldritch warmace'],
            ['id' => 50170, 'name' => 'gilded eldritch crescent moon spade'],
        ],
    ],
    63745 => [
        'name' => 'Timira Box',
        'loot' => [
            ['id' => 39233, 'name' => 'enchanted turtle amulet'],
            ['id' => 39166, 'name' => 'dawnfire pantaloons'],
            ['id' => 39164, 'name' => 'dawnfire sherwani'],
            ['id' => 39161, 'name' => 'feverbloom boots'],
            ['id' => 39158, 'name' => 'frostflower boots'],
            ['id' => 39167, 'name' => 'midnight sarong'],
            ['id' => 39165, 'name' => 'midnight tunic'],
            ['id' => 39156, 'name' => 'naga axe'],
            ['id' => 39157, 'name' => 'naga club'],
            ['id' => 39159, 'name' => 'naga crossbow'],
            ['id' => 50160, 'name' => 'naga katar'],
            ['id' => 39160, 'name' => 'naga quiver'],
            ['id' => 39163, 'name' => 'naga rod'],
            ['id' => 39155, 'name' => 'naga sword'],
            ['id' => 39162, 'name' => 'naga wand'],
            ['id' => 50262, 'name' => 'naga tanko'],
        ],
    ],
    63746 => [
        'name' => 'Drume Box',
        'loot' => [
            ['id' => 34158, 'name' => 'lion amulet'],
            ['id' => 34253, 'name' => 'lion axe'],
            ['id' => 50162, 'name' => 'lion claws'],
            ['id' => 34254, 'name' => 'lion hammer'],
            ['id' => 34150, 'name' => 'lion longbow'],
            ['id' => 34155, 'name' => 'lion longsword'],
            ['id' => 34157, 'name' => 'lion plate'],
            ['id' => 34151, 'name' => 'lion rod'],
            ['id' => 34154, 'name' => 'lion shield'],
            ['id' => 34156, 'name' => 'lion spangenhelm'],
            ['id' => 34153, 'name' => 'lion spellbook'],
            ['id' => 34152, 'name' => 'lion wand'],
        ],
    ],
    63747 => [
        'name' => 'Scarlett Box',
        'loot' => [
            ['id' => 31631, 'name' => 'cobra amulet'],
            ['id' => 30396, 'name' => 'cobra axe'],
            ['id' => 30395, 'name' => 'cobra club'],
            ['id' => 30393, 'name' => 'cobra crossbow'],
            ['id' => 30397, 'name' => 'cobra hood'],
            ['id' => 30400, 'name' => 'cobra rod'],
            ['id' => 30398, 'name' => 'cobra sword'],
            ['id' => 30399, 'name' => 'cobra wand'],
            ['id' => 50167, 'name' => 'cobra bo'],
        ],
    ],
    63748 => [
        'name' => 'Oberon Box',
        'loot' => [
            ['id' => 28714, 'name' => 'falcon circlet'],
            ['id' => 28715, 'name' => 'falcon coif'],
            ['id' => 28716, 'name' => 'falcon rod'],
            ['id' => 28717, 'name' => 'falcon wand'],
            ['id' => 28718, 'name' => 'falcon bow'],
            ['id' => 28719, 'name' => 'falcon plate'],
            ['id' => 28720, 'name' => 'falcon greaves'],
            ['id' => 28721, 'name' => 'falcon shield'],
            ['id' => 28722, 'name' => 'falcon escutcheon'],
            ['id' => 28723, 'name' => 'falcon longsword'],
            ['id' => 28724, 'name' => 'falcon battleaxe'],
            ['id' => 28725, 'name' => 'falcon mace'],
            ['id' => 50161, 'name' => 'falcon sai'],
        ],
    ],
    63749 => [
        'name' => 'Plunder Patriarch Box',
        'loot' => [
            ['id' => 39149, 'name' => 'alicorn headguard'],
            ['id' => 39150, 'name' => 'alicorn quiver'],
            ['id' => 39182, 'name' => 'alicorn ring'],
            ['id' => 39153, 'name' => 'arboreal crown'],
            ['id' => 39188, 'name' => 'arboreal ring'],
            ['id' => 39154, 'name' => 'arboreal tome'],
            ['id' => 39152, 'name' => 'arcanomancer folio'],
            ['id' => 39151, 'name' => 'arcanomancer regalia'],
            ['id' => 39185, 'name' => 'arcanomancer sigil'],
            ['id' => 50188, 'name' => 'ethereal coned hat'],
            ['id' => 39147, 'name' => 'spiritthorn armor'],
            ['id' => 39148, 'name' => 'spiritthorn helmet'],
            ['id' => 39179, 'name' => 'spiritthorn ring'],
        ],
    ],
    63750 => [
        'name' => 'Nightmare Beast Box',
        'loot' => [
            ['id' => 50190, 'name' => 'dark vision bandana'],
            ['id' => 29427, 'name' => 'dark whispers'],
            ['id' => 30342, 'name' => 'enchanted sleep shawl'],
        ],
    ],
    63751 => [
        'name' => 'Arbaziloth Box',
        'loot' => [
            ['id' => 49522, 'name' => 'inferniarch arbalest'],
            ['id' => 49523, 'name' => 'inferniarch battleaxe'],
            ['id' => 49527, 'name' => 'inferniarch blade'],
            ['id' => 49520, 'name' => 'inferniarch bow'],
            ['id' => 50250, 'name' => 'inferniarch claws'],
            ['id' => 49525, 'name' => 'inferniarch flail'],
            ['id' => 49524, 'name' => 'inferniarch greataxe'],
            ['id' => 49529, 'name' => 'inferniarch rod'],
            ['id' => 49530, 'name' => 'inferniarch slayer'],
            ['id' => 49528, 'name' => 'inferniarch wand'],
            ['id' => 49526, 'name' => 'inferniarch warhammer'],
            ['id' => 49531, 'name' => 'maliceforged helmet'],
            ['id' => 49532, 'name' => 'hellstalker visor'],
            ['id' => 49533, 'name' => 'dreadfire headpiece'],
            ['id' => 49534, 'name' => 'demonfang mask'],
            ['id' => 50189, 'name' => 'demon mengu'],
        ],
    ],
    63752 => [
        'name' => 'Soulwar Box',
        'loot' => [
            ['id' => 34088, 'name' => 'soulbleeder'],
            ['id' => 34089, 'name' => 'soulpiercer'],
            ['id' => 34099, 'name' => 'soulbastion'],
            ['id' => 34083, 'name' => 'soulshredder'],
            ['id' => 34090, 'name' => 'soultainter'],
            ['id' => 34091, 'name' => 'soulhexer'],
            ['id' => 34087, 'name' => 'soulmaimer'],
            ['id' => 34086, 'name' => 'soulcrusher'],
            ['id' => 34084, 'name' => 'soulbiter'],
            ['id' => 34092, 'name' => 'soulshanks'],
            ['id' => 34093, 'name' => 'soulstrider'],
            ['id' => 34098, 'name' => 'pair of soulstalkers'],
            ['id' => 34097, 'name' => 'pair of soulwalkers'],
            ['id' => 34094, 'name' => 'soulshell'],
        ],
    ],
    63753 => [
        'name' => 'Sanguine Box',
        'loot' => [
            ['id' => 43864, 'name' => 'sanguine blade'],
            ['id' => 43877, 'name' => 'sanguine bow'],
            ['id' => 43866, 'name' => 'sanguine cudgel'],
            ['id' => 43868, 'name' => 'sanguine hatchet'],
            ['id' => 43876, 'name' => 'sanguine legs'],
            ['id' => 43870, 'name' => 'sanguine razor'],
            ['id' => 43885, 'name' => 'sanguine rod'],
            ['id' => 43881, 'name' => 'sanguine greaves'],
            ['id' => 43882, 'name' => 'sanguine coil'],
            ['id' => 43879, 'name' => 'sanguine crossbow'],
            ['id' => 43884, 'name' => 'sanguine boots'],
        ],
    ],
    63754 => [
        'name' => "Gaz'haragoth Box",
        'loot' => [
            ['id' => 20071, 'name' => 'umbral axe'],
            ['id' => 20065, 'name' => 'umbral blade'],
            ['id' => 20083, 'name' => 'umbral bow'],
            ['id' => 20074, 'name' => 'umbral chopper'],
            ['id' => 20086, 'name' => 'umbral crossbow'],
            ['id' => 20080, 'name' => 'umbral hammer'],
            ['id' => 20077, 'name' => 'umbral mace'],
            ['id' => 20068, 'name' => 'umbral slayer'],
            ['id' => 20089, 'name' => 'umbral spellbook'],
            ['id' => 50164, 'name' => 'umbral katar'],
            ['id' => 20072, 'name' => 'umbral master axe'],
            ['id' => 20084, 'name' => 'umbral master bow'],
            ['id' => 20075, 'name' => 'umbral master chopper'],
            ['id' => 20087, 'name' => 'umbral master crossbow'],
            ['id' => 20081, 'name' => 'umbral master hammer'],
            ['id' => 20078, 'name' => 'umbral master mace'],
            ['id' => 20069, 'name' => 'umbral master slayer'],
            ['id' => 20090, 'name' => 'umbral master spellbook'],
            ['id' => 20066, 'name' => 'umbral masterblade'],
            ['id' => 50165, 'name' => 'umbral master katar'],
        ],
    ],
    63755 => [
        'name' => 'Zelos Box',
        'loot' => [
            ['id' => 50260, 'name' => 'death oyoroi'],
            ['id' => 31581, 'name' => 'bow of cataclysm'],
            ['id' => 31582, 'name' => 'galea mortis'],
            ['id' => 31737, 'name' => 'shadow cowl'],
            ['id' => 31583, 'name' => 'toga mortis'],
        ],
    ],
    63756 => [
        'name' => 'Mitmah Box',
        'loot' => [
            ['id' => 44648, 'name' => 'stoic iks boots'],
            ['id' => 44636, 'name' => 'stoic iks casque'],
            ['id' => 44620, 'name' => 'stoic iks chestplate'],
            ['id' => 44642, 'name' => 'stoic iks culet'],
            ['id' => 44643, 'name' => 'stoic iks faulds'],
            ['id' => 44637, 'name' => 'stoic iks headpiece'],
            ['id' => 44649, 'name' => 'stoic iks sandals'],
            ['id' => 44619, 'name' => 'stoic iks cuirass'],
            ['id' => 50291, 'name' => 'iks footwraps'],
            ['id' => 50255, 'name' => 'stoic iks robe'],
        ],
    ],
    63757 => [
        'name' => 'Amber Box',
        'loot' => [
            ['id' => 47371, 'name' => 'amber bow'],
            ['id' => 47377, 'name' => 'amber crossbow'],
            ['id' => 47376, 'name' => 'amber cudgel'],
            ['id' => 47370, 'name' => 'amber bludgeon'],
            ['id' => 47375, 'name' => 'amber axe'],
            ['id' => 47369, 'name' => 'amber greataxe'],
            ['id' => 47368, 'name' => 'amber slayer'],
            ['id' => 47374, 'name' => 'amber sabre'],
            ['id' => 47373, 'name' => 'amber rod'],
            ['id' => 47372, 'name' => 'amber wand'],
            ['id' => 50239, 'name' => 'amber kusarigama'],
        ],
    ],
    63758 => [
        'name' => 'Sugar Box',
        'loot' => [
        ],
    ],
    63759 => [
        'name' => 'Monster Box',
        'loot' => [
            ['id' => 40588, 'name' => 'antler-horn helmet'],
            ['id' => 40592, 'name' => "alchemist's boots"],
            ['id' => 40594, 'name' => "alchemist's notepad"],
            ['id' => 40593, 'name' => 'mutant bone boots'],
            ['id' => 40595, 'name' => 'mutant bone kilt'],
            ['id' => 40591, 'name' => 'mutated skin armor'],
            ['id' => 40590, 'name' => 'mutated skin legs'],
            ['id' => 40589, 'name' => 'stitched mutant hide legs'],
            ['id' => 50184, 'name' => 'mutant hide trousers'],
        ],
    ],
    63193 => [
        'name' => 'Warzone Box',
        'loot' => [
            ['id' => 27647, 'name' => 'gnome helmet'],
            ['id' => 27648, 'name' => 'gnome armor'],
            ['id' => 27649, 'name' => 'gnome legs'],
            ['id' => 27650, 'name' => 'gnome shield'],
            ['id' => 27651, 'name' => 'gnome sword'],
        ],
    ],
    61713 => [
        'name' => 'Destruction Box',
        'loot' => [
            ['id' => 27451, 'name' => 'axe of destruction'],
            ['id' => 27449, 'name' => 'blade of destruction'],
            ['id' => 27454, 'name' => 'hammer of destruction'],
            ['id' => 27452, 'name' => 'chopper of destruction'],
            ['id' => 27453, 'name' => 'mace of destruction'],
            ['id' => 27455, 'name' => 'bow of destruction'],
            ['id' => 27450, 'name' => 'slayer of destruction'],
            ['id' => 27458, 'name' => 'rod of destruction'],
            ['id' => 27456, 'name' => 'crossbow of destruction'],
            ['id' => 27457, 'name' => 'wand of destruction'],
        ],
    ],
    61703 => [
        'name' => 'Pale Box',
        'loot' => [
            ['id' => 32617, 'name' => 'fabulous legs'],
            ['id' => 50185, 'name' => 'jade legs'],
            ['id' => 32628, 'name' => 'ghost chestplate'],
            ['id' => 32619, 'name' => 'pair of nightmare boots'],
            ['id' => 32616, 'name' => 'phantasmal axe'],
            ['id' => 32636, 'name' => 'ring of souls'],
            ['id' => 32618, 'name' => 'soulful legs'],
        ],
    ],
];
