<?php
defined('MYAAC') or die('Direct access not allowed!');

$commons = [
    ['id' => 64086, 'name' => '10-35x RavynCore Coins'],
    ['id' => 61869, 'name' => '1-3x RavynCore Token'],
    ['id' => 37110, 'name' => '1-5x Exalted Core'],
    ['id' => 61862, 'name' => '1-3x Bag of Dusts'],
    ['id' => 60581, 'name' => '1-10x Stone Dust'],
    ['id' => 16129, 'name' => '10x Major Crystalline Token'],
    ['id' => 35563, 'name' => '10-25x Magic Shield Potion'],
    ['id' => 61865, 'name' => '5x Prey Wildcard'],
    ['id' => 61866, 'name' => '10x Prey Wildcard'],
    ['id' => 61867, 'name' => '20x Prey Wildcard'],
    ['id' => 36723, 'name' => '1-2x Kooldown-Aid'],
    ['id' => 36724, 'name' => '1-2x Strike Enhancement'],
    ['id' => 36725, 'name' => '1-2x Stamina Extension'],
    ['id' => 36726, 'name' => '1-2x Charm Upgrade'],
    ['id' => 36727, 'name' => '1-2x Wealth Duplex'],
    ['id' => 36728, 'name' => '1-2x Bestiary Betterment'],
    ['id' => 36729, 'name' => '1-2x Fire Resilience'],
    ['id' => 36730, 'name' => '1-2x Ice Resilience'],
    ['id' => 36731, 'name' => '1-2x Earth Resilience'],
    ['id' => 36732, 'name' => '1-2x Energy Resilience'],
    ['id' => 36733, 'name' => '1-2x Holy Resilience'],
    ['id' => 36734, 'name' => '1-2x Death Resilience'],
    ['id' => 36735, 'name' => '1-2x Physical Resilience'],
    ['id' => 36736, 'name' => '1-2x Fire Amplification'],
    ['id' => 36737, 'name' => '1-2x Ice Amplification'],
    ['id' => 36738, 'name' => '1-2x Earth Amplification'],
    ['id' => 36739, 'name' => '1-2x Energy Amplification'],
    ['id' => 36740, 'name' => '1-2x Holy Amplification'],
    ['id' => 36741, 'name' => '1-2x Death Amplification'],
    ['id' => 36742, 'name' => '1-2x Physical Amplification'],
    ['id' => 28485, 'name' => '1-5x Strawberry Cupcake'],
    ['id' => 28484, 'name' => '1-5x Blueberry Cupcake'],
    ['id' => 61560, 'name' => 'Green Spark'],
    ['id' => 61556, 'name' => 'Green Magic'],
    ['id' => 61558, 'name' => 'Yellow Spark'],
    ['id' => 61554, 'name' => 'Yellow Magic'],
    ['id' => 61559, 'name' => 'Blue Spark'],
    ['id' => 61555, 'name' => 'Blue Magic'],
    ['id' => 61561, 'name' => 'Red Spark'],
    ['id' => 61557, 'name' => 'Red Magic'],
];

return [
    'tokenId' => 64087,
    'tokenName' => 'Roulette Token',
    'spinOptions' => [1, 5, 10, 25, 50, 100],
    'spinningBonus' => [
        ['spins' => 25, 'reward' => 'Ruby Outfit', 'itemId' => 64040, 'count' => 1],
        ['spins' => 50, 'reward' => 'Crystal Outfit', 'itemId' => 64041, 'count' => 1],
        ['spins' => 75, 'reward' => 'Emerald Outfit', 'itemId' => 64042, 'count' => 1],
        ['spins' => 100, 'reward' => 'Silver Outfit', 'itemId' => 64043, 'count' => 1],
    ],
    'commons' => $commons,
    'roulettes' => [
        [
            'id' => 'norte',
            'name' => 'Roleta do Norte',
            'exclusive' => [
                ['id' => 64040, 'name' => 'Ruby Outfit'],
                ['id' => 64041, 'name' => 'Crystal Outfit'],
                ['id' => 64042, 'name' => 'Emerald Outfit'],
                ['id' => 64043, 'name' => 'Silver Outfit'],
                ['id' => 64101, 'name' => 'Boneheart Backpack'],
            ],
        ],
        [
            'id' => 'esquerda',
            'name' => 'Roleta da Esquerda',
            'exclusive' => [
                ['id' => 64087, 'name' => '2x Roulette Token'],
                ['id' => 43946, 'name' => '1-2x Abridged Promotion Scroll'],
                ['id' => 43947, 'name' => '1-2x Basic Promotion Scroll'],
                ['id' => 43948, 'name' => '1-2x Revised Promotion Scroll'],
                ['id' => 43949, 'name' => '1-2x Extended Promotion Scroll'],
                ['id' => 64114, 'name' => '1-2x Epic Promotion Scroll'],
                ['id' => 64085, 'name' => 'Bag of Stone 0'],
                ['id' => 63100, 'name' => '3x Basic Upgrade Stone'],
                ['id' => 63101, 'name' => '2x Medium Upgrade Stone'],
                ['id' => 63099, 'name' => 'Epic Upgrade Stone'],
            ],
        ],
        [
            'id' => 'sul',
            'name' => 'Roleta do Sul',
            'exclusive' => [
                ['id' => 39546, 'name' => 'Primal Bag'],
                ['id' => 43898, 'name' => 'Bag You Covet'],
                ['id' => 34109, 'name' => 'Bag You Desire'],
                ['id' => 63787, 'name' => '100x Charm Points'],
                ['id' => 63743, 'name' => 'Ratmiral Box'],
                ['id' => 63744, 'name' => 'Brainstealer Box'],
                ['id' => 63745, 'name' => 'Timira Box'],
                ['id' => 63748, 'name' => 'Oberon Box'],
                ['id' => 63746, 'name' => 'Drume Box'],
                ['id' => 63747, 'name' => 'Scarlett Box'],
                ['id' => 63749, 'name' => 'Plunder Box'],
                ['id' => 63750, 'name' => 'Nightmare Box'],
                ['id' => 63751, 'name' => 'Arbaziloth Box'],
                ['id' => 63752, 'name' => 'Soulwar Box'],
                ['id' => 63753, 'name' => 'Sanguine Box'],
                ['id' => 63754, 'name' => "Gaz'haragoth Box"],
                ['id' => 63755, 'name' => 'Zelos Box'],
                ['id' => 63756, 'name' => 'Mitmah Box'],
                ['id' => 63757, 'name' => 'Amber Box'],
                ['id' => 63758, 'name' => 'Sugar Box'],
                ['id' => 63759, 'name' => 'Monster Box'],
                ['id' => 63193, 'name' => 'Warzone Box'],
                ['id' => 61713, 'name' => 'Inferniarch Box'],
                ['id' => 61703, 'name' => 'Pale Box'],
            ],
        ],
    ],
];
