darkborder = "#22324b"
lightborder = "#2b3f5f"
vdarkborder = "#121c2f"

logo_monster = "RavynCore"

; List: newcomer,gallery,premium,poll,highscores,networks - discord,donate,searchchar,rashid
boxes = "rank,discord,serversave,donate,searchchar,rashid,poll"

; leave empty to disable
network_facebook = "tibia"

; leave empty to disable
network_twitter = "tibia"

background_image = ""
logo_image = "tibia-logo-artwork-top.gif"
gallery_image_id_from_database = 1
